world:
  width: 200
  height: 200
  continent-size: 20
  aging-speed: .5

  material-heights:
    deep-shallow-water-border: 0.44
    shallow-water-sand-border: 0.49
    sand-shrub-border: 0.52
    shrub-grass-border: 0.53
    grass-hill-border: 0.6
    hill-mountain-border: 0.64
    mountain-snow-border: 0.71

  decorations:
    deep-water:
      None: 100
    shallow-water:
      None: 100
    sand:
      palm: 5
      None: 95
    shrub:
      None: 100
    grass:
      tree: 30
      pine: 10
      red-rose: 15
      pink-rose: 1
      None: 44
    hill:
      pine: 40
      red-rose: 5
      pink-rose: 1
      None: 55
    mountain:
      edelweiss: 6
      None: 94
    snow:
      blue-rose: 0.1
      None: 99.9